### ISSUE TITLE
Cannot use logard in Vitest

### ISSUE THREAD

**Issue by SeppeP** [everbuild/logard#1]
Hello good sir

I'm writing some tests in Vitest and when trying to import anything from logard, I get an error.

In my use case, I wanted to mock a TrackingScope 

```
    import TrackingScope from 'logard/dist/src/TrackingScope.js';

    const scope = new TrackingScope(params, {});
```

this results in this error:

``` 
Failed to resolve import "logard/dist/src/TrackingScope.js" from "fileToTest.test.ts". Does the file exist?'
```

**Comment by everbuild** [comment]
Hi @SeppeP, good to hear from you!

`TrackingScope` is intended as an internal concern, but most APIs just need a subclass of Scope. So you could create a subclass that you can specialize for your testing purposes, as shown below. Does this work for you?
This doesn't allow calling `Loader.getResult` though (it really needs a TrackingScope to determine when a previous result can be returned), but I would advise mocking that specific function if needed as that seems outside of the scope of a typical unit test.

```typescript
import { ParamSource, RouteParams, RouteAttributes, Scope } from 'logard';

class TestScope extends Scope {
  constructor(
    public params: Partial<RouteParams> & { attribs?: RouteAttributes },
  ) {
    super();
  }

  protected getParamValue(name: string, source: ParamSource): Array<string> | undefined {
    return this.params[source]?.[name];
  }

  getAttribute<T>(name: string): T | undefined {
    return this.params.attribs?.[name];
  }
}
```

**Comment by SeppeP** [comment]
Thank you for the great advice. I got it working now.
